from sqlalchemy import Column, String, Integer, Float, Boolean, DateTime, Text, JSON
from sqlalchemy.sql import func
from app.database import Base


class ChatMessage(Base):
    """Stored chat messages for conversation history."""
    __tablename__ = "chat_messages"

    id = Column(String, primary_key=True, default=lambda: f"msg_{__import__('uuid').uuid4().hex[:12]}")
    user_id = Column(String, nullable=False, index=True)
    role = Column(String(20), nullable=False)  # "user" or "assistant"
    content = Column(Text, nullable=False)
    metadata_json = Column(JSON, nullable=True)  # Extra info like risks, suggestions

    created_at = Column(DateTime(timezone=True), server_default=func.now())

    def __repr__(self):
        return f"<ChatMessage {self.id} ({self.role})>"


class RiskAlert(Base):
    """Persisted risk alerts generated by the AI engine."""
    __tablename__ = "risk_alerts"

    id = Column(String, primary_key=True, default=lambda: f"alert_{__import__('uuid').uuid4().hex[:12]}")
    user_id = Column(String, nullable=True, index=True)  # Null if global alert
    risk_type = Column(String(50), nullable=False)  # flood, storm, heat
    severity = Column(String(20), nullable=False)  # High, Moderate, Low
    title = Column(String(255), nullable=False)
    description = Column(Text, nullable=False)
    percentage = Column(Float, nullable=False)
    latitude = Column(Float, nullable=True)
    longitude = Column(Float, nullable=True)
    is_active = Column(Boolean, default=True)

    created_at = Column(DateTime(timezone=True), server_default=func.now())
    resolved_at = Column(DateTime(timezone=True), nullable=True)

    def __repr__(self):
        return f"<RiskAlert {self.id} ({self.risk_type}: {self.severity})>"


class Recommendation(Base):
    """Persisted AI recommendations."""
    __tablename__ = "recommendations"

    id = Column(String, primary_key=True, default=lambda: f"rec_{__import__('uuid').uuid4().hex[:12]}")
    user_id = Column(String, nullable=False, index=True)
    category = Column(String(50), nullable=False)  # general, farm, solar
    text = Column(Text, nullable=False)
    priority = Column(Integer, default=0)  # Higher = more urgent
    is_read = Column(Boolean, default=False)
    is_actioned = Column(Boolean, default=False)

    created_at = Column(DateTime(timezone=True), server_default=func.now())

    def __repr__(self):
        return f"<Recommendation {self.id} ({self.category})>"
